### ISSUE TITLE
Something went wrong.

### ISSUE THREAD

**Issue by dl-eric** [dl-eric/ACMbot#2]
TypeError: Cannot read property 'forEach' of undefined.
at app.post (/app/index.js:64:13)

Not sure why this happens. Min pls help.

**Comment by MinhyukPark** [comment]
Take out the for-each loop. There's already a function in Facebook.js that does this hence it is redundant. Once you get rid if lines 64 and 65 this issue should be resolved.

**Comment by MinhyukPark** [comment]
Also refactor the const declarations and potentially other code from event to data.

**Comment by MinhyukPark** [comment]
Fixed by merging pull request #7. Case dismissed.
